feat: Created target_performance data
Pinpoint-Simulations/PPS777 pull request #5
Opened 2021-04-28 02:08 UTC by Spherrrical

# Title

## Discord username

Spherical#0001
## Changes you have made

Added a performance cfg file with stall data.
## References used

https://contentzone.eurocontrol.int/aircraftperformance/details.aspx?ICAO=B77W
## Images and/or videos of changes (if needed)

## Additional comments

**QA testing coming soon**

2021-04-28 02:17 UTC, scoopscode commented on PinpointB777/PackageSources/SimObjects/Airplanes/Pinpoint_B777/target_performance.cfg
> +wing_area = 4998,0.1;
What units is this in?

2021-04-28 02:18 UTC, Spherrrical commented on PinpointB777/PackageSources/SimObjects/Airplanes/Pinpoint_B777/target_performance.cfg
> +wing_area = 4998,0.1;
Wait...I need to fix this.

2021-04-28 02:22 UTC, Spherrrical commented on PinpointB777/PackageSources/SimObjects/Airplanes/Pinpoint_B777/target_performance.cfg
> +wing_area = 4998,0.1;
This should be in feet.

2021-04-28 03:35 UTC, scoopscode requested changes

2021-04-28 03:35 UTC, scoopscode commented on PinpointB777/PackageSources/SimObjects/Airplanes/Pinpoint_B777/target_performance.cfg
> +max_hp = 37828,0.1;
I believe this is 55,000-60,000 hp.

2021-04-29 15:30 UTC, Spherrrical commented on PinpointB777/PackageSources/SimObjects/Airplanes/Pinpoint_B777/target_performance.cfg
> +max_hp = 37828,0.1;
Resolved.

2021-04-29 18:01 UTC, scoopscode commented on PinpointB777/PackageSources/SimObjects/Airplanes/Pinpoint_B777/target_performance.cfg
> +max_hp = 37828,0.1;
Is this indicating 37,828 hp per engine or for the entire aircraft?

2021-04-30 08:49 UTC, Spherrrical commented on PinpointB777/PackageSources/SimObjects/Airplanes/Pinpoint_B777/target_performance.cfg
> +max_hp = 37828,0.1;
Entire aircraft.

2021-04-30 12:31 UTC, scoopscode commented on PinpointB777/PackageSources/SimObjects/Airplanes/Pinpoint_B777/target_performance.cfg
> +max_hp = 37828,0.1;
Pretty sure one engine does around 40,000 hp. Might wanna check your stats.

2021-05-04 13:26 UTC, scoopscode commented on PinpointB777/PackageSources/SimObjects/Airplanes/Pinpoint_B777/target_performance.cfg
> +max_hp = 37828,0.1;
@Spherrrical ...

2021-05-13 15:11 UTC, scoopscode commented
Since @Spherrrical seems to not really care about this PR, I will be closing it and wait for him to resolve/fix requested changes

2021-05-18 04:14 UTC, scoopscode commented
@Spherrrical check #8

2021-05-18 04:14 UTC, Spherrrical commented on PinpointB777/PackageSources/SimObjects/Airplanes/Pinpoint_B777/target_performance.cfg
> +max_hp = 37828,0.1;
Added it @scoopscode

2021-05-18 04:15 UTC, scoopscode commented
Ok strange I thought I opened one today for this but let me review

2021-05-18 04:16 UTC, scoopscode commented
LGTM!

2021-05-18 04:16 UTC, merged